# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-18 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_answer_stance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([]),
        ),
    ]
