# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20160614_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
    ]
