# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_answer_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([]),
        ),
    ]
