# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_suggestedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedquestion',
            name='related_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
