# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_suggestedquestion_related_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='con_label',
            field=models.TextField(default='Against'),
        ),
        migrations.AddField(
            model_name='question',
            name='pro_label',
            field=models.TextField(default='For'),
        ),
        migrations.AlterField(
            model_name='suggestedquestion',
            name='related_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question', verbose_name='Approved to question'),
        ),
    ]
