# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20160627_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='con_label',
            field=models.CharField(default='Against', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='pro_label',
            field=models.CharField(default='For', max_length=250),
        ),
    ]
