# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20160627_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='even_more',
            field=models.TextField(default='coming soon'),
            preserve_default=False,
        ),
    ]
