# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_question_even_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
