# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20160628_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_skipped',
            field=models.BooleanField(default=False),
        ),
    ]
