# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_answer_is_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='stance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stances.Stance'),
        ),
        migrations.AlterField(
            model_name='question',
            name='even_more',
            field=models.TextField(default='Coming soon'),
        ),
    ]
