# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_remove_answer_is_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='stance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stances.Stance'),
        ),
    ]
