# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20160629_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='na_label',
            field=models.CharField(default='Not available', max_length=250),
        ),
        migrations.AddField(
            model_name='question',
            name='num_na_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
