# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_auto_20160714_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='num_con_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_pro_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
