# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_auto_20160714_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skipanswer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='skipanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='skipanswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='SkipAnswer',
        ),
    ]
