# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_auto_20160718_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default='red'),
            preserve_default=False,
        ),
    ]
