# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='statement',
            field=models.TextField(default='coming soon'),
            preserve_default=False,
        ),
    ]
