# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-18 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0002_auto_20160518_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stance',
            name='profile',
        ),
    ]
