# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-18 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0003_remove_stance_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stancecomment',
            name='profile',
        ),
    ]
