# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0004_remove_stancecomment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stance',
            name='stamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
