# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0005_auto_20160612_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='stamp',
            field=models.DateField(blank=True, null=True, verbose_name='Timestamp'),
        ),
    ]
