# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0007_stancehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stancehistory',
            name='stance',
        ),
        migrations.RemoveField(
            model_name='stancehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='StanceHistory',
        ),
    ]
