# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0008_auto_20160614_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='choice',
            field=models.CharField(choices=[(b'p', b'For'), (b'c', b'Against'), (b'u', b'unsure')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stancecomment',
            name='choice',
            field=models.CharField(choices=[(b'p', b'For'), (b'c', b'Against'), (b'u', b'unsure')], max_length=1, null=True),
        ),
    ]
