# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0009_auto_20160620_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='choice',
            field=models.CharField(choices=[(b'p', b'Pro'), (b'c', b'Con')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stancecomment',
            name='choice',
            field=models.CharField(choices=[(b'p', b'Pro'), (b'c', b'Con')], max_length=1, null=True),
        ),
    ]
