# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0010_auto_20160628_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stance',
            name='num_agree',
        ),
    ]
