# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0011_remove_stance_num_agree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='choice',
            field=models.CharField(choices=[(b'p', b'Pro'), (b'c', b'Con'), (b'u', b'Unsure')], default='p', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stancecomment',
            name='choice',
            field=models.CharField(choices=[(b'p', b'Pro'), (b'c', b'Con'), (b'u', b'Unsure')], max_length=1, null=True),
        ),
    ]
