# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0012_auto_20160711_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stance',
            name='stance_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
