# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0013_auto_20160711_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='num_stars',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stance',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
