# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0015_stance_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stanceparent', to='stances.Stance'),
        ),
    ]
