# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0016_stance_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stancecomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='stancecomment',
            name='stance',
        ),
        migrations.RemoveField(
            model_name='stancecomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='StanceComment',
        ),
    ]
