# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0018_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='stance',
            name='num_agree',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
