# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-15 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=datetime.datetime(2016, 5, 15, 14, 45, 30, 825703, tzinfo=utc), upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
