# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-18 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='party',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
