# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160518_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
    ]
