# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_notification_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_agrees',
            field=models.BooleanField(default=True),
        ),
    ]
