# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20160531_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_famous',
            field=models.BooleanField(default=False),
        ),
    ]
