# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20160602_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=profiles.models.get_file_path),
        ),
    ]
