# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_follow'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('follower', 'followed')]),
        ),
    ]
