# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20160707_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileverification',
            options={'verbose_name': 'Profile verification', 'verbose_name_plural': 'Profile verification'},
        ),
    ]
