# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20160721_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification_replies',
            new_name='notification_follower',
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_stance_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_thread_comment',
            field=models.BooleanField(default=True),
        ),
    ]
