# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20160721_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification_stance_comment',
            new_name='notification_comment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notification_thread_comment',
        ),
    ]
