# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_profile_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_process_complete',
            field=models.BooleanField(default=False),
        ),
    ]
