"""
Django settings for webmonitoring project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

from .affiliate import *
from .core import *
from .sites import *
from .databases import *
from .installed_apps import *
from .localization import *
from .middleware_classes import *
from .security import *
from .static import *
from .templates import *
from .utils import *
from .compressor import *
from .stripe import *
from .tinymce import *
from .thumbnail import *
from .recaptcha import *
from .cors import *
from .logging import *

try:
    from .__local__ import *
except:
    pass