INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'captcha',
    'tinymce',
    'gunicorn',
    'compressor',
    'django_cleanup',
#     'debug_toolbar',
    'tabbed_admin',
    'pinax.stripe',
    'easy_thumbnails',
    'corsheaders',
    
    'apps.affiliate',
    'apps.base',
    'apps.seesoon',
    'apps.canvas_gadget',
    'apps.demobooth',
    'apps.feedback',
    'apps.accounts',
    'apps.billing',
    'apps.projects',
    'apps.sample',
    'apps.webgl',
    'apps.gmail',
)