# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0037_material_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('show_on_main', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=256)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'sample',
                'ordering': ['id'],
                'verbose_name_plural': 'samples',
            },
        ),
    ]
