# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
