# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('canvas_gadget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('homepage_header_image', models.ImageField(upload_to='sitemedia')),
                ('homepage_header_text_first', models.CharField(max_length=128)),
                ('homepage_header_text_second', models.CharField(max_length=256)),
                ('homepage_header_text_button', models.CharField(max_length=256)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='subscription_template',
            field=models.IntegerField(choices=[(1, 'silver'), (2, 'gold'), (3, 'platinum')], default=1),
        ),
    ]
