# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0003_auto_20160921_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageRowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='sitemedia')),
                ('label', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=512)),
                ('sitesettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canvas_gadget.SiteSettings')),
            ],
            options={
                'verbose_name': 'home page row item',
                'verbose_name_plural': 'home page row items',
            },
        ),
    ]
