# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0004_homepagerowitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_first_sample_label',
            field=models.CharField(default='Affordability', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_first_sample_text',
            field=tinymce.models.HTMLField(default="            <p>A new experience within your budget.</p>            <p>Quality 3D models that won't break your bank Cost-efficient web hosting.</p>            <p>Compelling demos lead to increased revenue greater client satisfaction and tangible results.</p>"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_second_sample_label',
            field=models.CharField(default='Your Product In 3D', max_length=64),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_second_sample_text',
            field=tinymce.models.HTMLField(default='            <p>What if you could demonstrate your product in a whole new way that will encourage your customers to buy?</p>            <ul>                <li>Give users a feel for your product before they buy.</li>                <li>Instantly call out product features.</li>                <li>Ignite your users creativity.</li>                <li>Spark your users genius.</li>            </ul>'),
        ),
        migrations.AlterField(
            model_name='homepagerowitem',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_header_text_button',
            field=models.CharField(default='sign up for offers', max_length=256),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_header_text_first',
            field=tinymce.models.HTMLField(default='CONVERT YOUR ECOMMERCE STORE INTO A 3D EXPERIENCE', max_length=128),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_header_text_second',
            field=tinymce.models.HTMLField(default='Give your customers an amazing buying experience! Easily implement with one line of code.', max_length=256),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_text_how_it_work',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
