# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0005_auto_20160922_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_label_how_it_work',
            field=models.CharField(default='How It Works ', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_text_how_it_work',
            field=tinymce.models.HTMLField(default="Bringing attention to your product can be a real challenge, especially         if you only have a couple of simple images and a description. Stop telling them         about your product and start letting them experience it for themselves.<br />Don&rsquo;t         worry, implementing Canvas Gadget's 3D marketing content is as easy as adding a single line         of code to your website."),
        ),
    ]
