# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0006_auto_20160925_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_form_text',
            field=tinymce.models.HTMLField(default='Have a question or a comment?<br>Feel free to let us know.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_header_image',
            field=models.ImageField(blank=True, null=True, upload_to='sitemedia'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_header_text',
            field=models.CharField(default='Drop Us A Line', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_message_label',
            field=models.CharField(default='Message', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_message_text',
            field=tinymce.models.HTMLField(default='Lorem ipsum dolor sit amet'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feedbackpage_submit_button_text',
            field=models.CharField(default='Send Message', max_length=128),
        ),
    ]
