# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0007_auto_20160925_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='feedbackpage_header_text',
            new_name='feedbackpage_social_text',
        ),
    ]
