# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0008_auto_20160925_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='homepage_label_how_it_work',
            field=models.CharField(default='Stop Losing Customers - Start Engaging', max_length=64),
        ),
    ]
