# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_project_owner'),
        ('canvas_gadget', '0009_auto_20160926_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
