# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0010_projectrequest_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequest',
            name='project',
        ),
    ]
