# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0011_remove_projectrequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'new'), (1, 'on review'), (2, 'ready')], default=0),
        ),
    ]
