# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
        ('accounts', '0002_auto_20161113_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliate.Affiliate'),
        ),
    ]
