# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-05 05:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'environment image',
                'verbose_name_plural': 'environment images',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LensFlare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'lens flare',
                'verbose_name_plural': 'lens flares',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2016, 6, 5, 5, 30, 46, 168037, tzinfo=utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Plan'),
        ),
    ]
