# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160605_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '3d model',
                'verbose_name_plural': '3d models',
            },
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/environment_image'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/lens_flare'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(upload_to='projects/material'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='model3d',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
