# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 07:13
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160608_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to=apps.projects.models.upload_model_to_media),
        ),
    ]
