# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 07:47
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160608_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('file', models.FileField(upload_to=apps.projects.models.upload_texture_to_media)),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'verbose_name_plural': 'textures',
                'ordering': ['id'],
                'verbose_name': 'texture',
            },
        ),
    ]
