# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 06:22
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20160611_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('show_background', models.BooleanField(default=False)),
                ('gradient_top_hue', models.FloatField(default=0.5)),
                ('gradient_top_lightness', models.FloatField(default=0.5)),
                ('gradient_bottom_hue', models.FloatField(default=0.5)),
                ('gradient_bottom_lightness', models.FloatField(default=0.5)),
                ('gradient_offset', models.FloatField(default=0)),
                ('show_ground_plane', models.BooleanField(default=False)),
                ('ground_plane', models.ImageField(upload_to=apps.projects.models.upload_environment_to_media)),
                ('ground_plane_scale', models.FloatField(default=1.0)),
                ('show_shadow', models.BooleanField(default=False)),
                ('show_reflective', models.BooleanField(default=False)),
                ('reflective_amount', models.FloatField(default=0)),
                ('environment_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.EnvironmentImage')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'environment',
                'ordering': ['id'],
                'verbose_name_plural': 'environments',
            },
        ),
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.projects.models.upload_model_to_media),
        ),
    ]
