# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160619_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensflare',
            name='band_1',
            field=models.ImageField(default='', upload_to='projects/lens_flare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensflare',
            name='band_2',
            field=models.ImageField(default='', upload_to='projects/lens_flare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensflare',
            name='hexigon_shape',
            field=models.ImageField(default='', upload_to='projects/lens_flare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lensflare',
            name='main_flare',
            field=models.ImageField(default='', upload_to='projects/lens_flare'),
            preserve_default=False,
        ),
    ]
