# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 17:19
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160622_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='environment_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.EnvironmentImage'),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_bottom_hue',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_bottom_lightness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_offset',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_top_hue',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='project',
            name='gradient_top_lightness',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='project',
            name='ground_plane',
            field=models.ImageField(blank=True, default='', null=True, upload_to=apps.projects.models.upload_environment_to_media),
        ),
        migrations.AddField(
            model_name='project',
            name='ground_plane_scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='project',
            name='reflective_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='show_background',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='show_ground_plane',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='show_reflective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='show_shadow',
            field=models.BooleanField(default=False),
        ),
    ]
