# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20160626_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLensFlare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('lensflare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.LensFlare')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'model lens flares',
                'verbose_name': 'model lens flare',
            },
        ),
        migrations.CreateModel(
            name='ModelMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('compNum', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Material')),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'model materials',
                'verbose_name': 'model material',
            },
        ),
        migrations.AlterModelOptions(
            name='callout',
            options={'ordering': ['id'], 'verbose_name': 'callout', 'verbose_name_plural': 'callouts'},
        ),
    ]
