# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 15:24
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20160630_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='skybox',
            name='nx',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_nx),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skybox',
            name='ny',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_ny),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skybox',
            name='nz',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_nz),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skybox',
            name='px',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_px),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skybox',
            name='py',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_py),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skybox',
            name='pz',
            field=models.ImageField(default='', upload_to=apps.projects.models.upload_skybox_pz),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skybox',
            name='thumbnail',
            field=models.ImageField(upload_to=apps.projects.models.upload_skybox_thumbnail),
        ),
    ]
