# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20160630_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchorstyle',
            name='image',
            field=models.ImageField(upload_to='style/anchor'),
        ),
        migrations.AlterField(
            model_name='calloutstyle',
            name='image',
            field=models.ImageField(upload_to='style/callout'),
        ),
        migrations.AlterField(
            model_name='linestyle',
            name='image',
            field=models.ImageField(upload_to='style/line'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thumbnail',
            field=models.ImageField(upload_to='material'),
        ),
    ]
