# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160630_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skybox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Skybox'),
        ),
    ]
