# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_auto_20160630_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groundplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='groundplane')),
            ],
            options={
                'verbose_name': 'groundplane',
                'verbose_name_plural': 'groundplanes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='skybox',
            options={'ordering': ['name'], 'verbose_name': 'skybox', 'verbose_name_plural': 'skyboxes'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='ground_plane',
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='band_1',
            field=models.ImageField(upload_to='lens_flare'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='band_2',
            field=models.ImageField(upload_to='lens_flare'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='hexigon_shape',
            field=models.ImageField(upload_to='lens_flare'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='main_flare',
            field=models.ImageField(upload_to='lens_flare'),
        ),
        migrations.AlterField(
            model_name='lensflare',
            name='thumbnail',
            field=models.ImageField(upload_to='lens_flare'),
        ),
    ]
