# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20160630_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groundplane',
            options={'ordering': ['id'], 'verbose_name': 'groundplane', 'verbose_name_plural': 'groundplanes'},
        ),
        migrations.AlterModelOptions(
            name='skybox',
            options={'ordering': ['id'], 'verbose_name': 'skybox', 'verbose_name_plural': 'skyboxes'},
        ),
        migrations.AddField(
            model_name='model3d',
            name='camera_pos_x',
            field=models.FloatField(default=0.0045000000000007334),
        ),
        migrations.AddField(
            model_name='model3d',
            name='camera_pos_y',
            field=models.FloatField(default=0.7674),
        ),
        migrations.AddField(
            model_name='model3d',
            name='camera_pos_z',
            field=models.FloatField(default=-2.9879999999999995),
        ),
        migrations.AlterUniqueTogether(
            name='modelmaterial',
            unique_together=set([('model3d', 'compNum')]),
        ),
    ]
