# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20160702_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestyle',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='style/line'),
        ),
    ]
