# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-16 14:06
from __future__ import unicode_literals

import apps.projects.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20160706_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('name', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=64)),
                ('forward', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('reverse', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to=apps.projects.models.upload_animation_to_media)),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'verbose_name_plural': 'animations',
                'ordering': ['id'],
                'verbose_name': 'animation',
            },
        ),
    ]
