# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_animation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('type', models.IntegerField(choices=[(0, 'cascade'), (1, 'individual')], default=0)),
                ('model3d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'animation model',
                'verbose_name_plural': 'animation models',
            },
        ),
        migrations.RemoveField(
            model_name='animation',
            name='model3d',
        ),
        migrations.AddField(
            model_name='animation',
            name='animation_model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.AnimationModel'),
        ),
    ]
