# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20160717_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='animation_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.AnimationModel'),
        ),
    ]
