# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 15:59
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_animation_thumbnail_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.projects.models.upload_project_logo),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
