# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20160725_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='rotate_camera',
            field=models.BooleanField(default=True),
        ),
    ]
