# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_project_slim_scroll_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slim_scroll_color',
            field=models.CharField(default='#ffffff', help_text='HEX color, as #RRGGBB', max_length=7),
        ),
    ]
