# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-30 16:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20160727_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
