# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20160816_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmaterial',
            name='subCompNum',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='modelmaterial',
            unique_together=set([('model3d', 'material', 'compNum', 'subCompNum')]),
        ),
    ]
