# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20160816_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='camera_max_distance',
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name='model3d',
            name='camera_min_distance',
            field=models.FloatField(default=1.5),
        ),
    ]
