# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 06:51
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20160819_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to=apps.projects.models.upload_model_to_media),
        ),
    ]
