# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_gadget', '0011_remove_projectrequest_project'),
        ('projects', '0046_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectrequest',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas_gadget.ProjectRequest'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
