# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 16:58
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20161112_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', null=True, upload_to=apps.projects.models.upload_model_to_media),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='thumbnail_tmp',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='', null=True, upload_to=apps.projects.models.upload_model_to_media),
        ),
    ]
