# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 18:05
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_auto_20161130_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.projects.models.upload_model2d_to_media)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
