# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_animation_external_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='external_link',
            new_name='logo_url',
        ),
    ]
