# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 17:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

def create_default_light(apps, schema_editor):
    Light = apps.get_model('projects', "Light")
    light = Light(id=1, name='Default Light')
    light.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20170204_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(default=[{'intensity': 1, 'position': {'x': 0, 'y': 1, 'z': 0}, 'range': 1, 'type': 'HemisphericLight'}, {'direction': {'x': 0, 'y': 1, 'z': 0}, 'intensity': 0.4, 'position': {'x': 0, 'y': -5, 'z': 0}, 'range': 5, 'type': 'DirectionalLight'}, {'intensity': 1, 'position': {'x': 0, 'y': -1, 'z': 0}, 'range': 1, 'type': 'HemisphericLight'}])),
            ],
        ),
        migrations.RunPython(create_default_light)
    ]
