# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20170205_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='normal_map',
            field=models.ImageField(blank=True, null=True, upload_to='material'),
        ),
    ]
