# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_project_show_cg_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coupon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
