# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20170227_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='popupp_position_left',
            new_name='popup_position_left',
        ),
    ]
