# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_auto_20170227_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='popup_position_left',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='popup_position_top',
            field=models.PositiveIntegerField(blank=True, default=50),
        ),
    ]
