# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20170227_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='popup_position_left',
        ),
        migrations.RemoveField(
            model_name='project',
            name='popup_position_top',
        ),
        migrations.AddField(
            model_name='project',
            name='popup_extra_style',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
