# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20170227_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='popup_extra_style',
            field=models.CharField(blank=True, help_text='for example: <code>top: 50%; left: 50%; transform: translate(-50%, -50%);</code>', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='popup_text',
            field=models.CharField(blank=True, help_text='"Click or swipe to interact with the product" by default', max_length=32, null=True),
        ),
    ]
