# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20170227_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coupon',
        ),
    ]
