# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0006_coupon'),
        ('projects', '0067_project_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subscription_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Subscription'),
        ),
    ]
