# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_auto_20170312_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='subscription_field',
            new_name='subscription',
        ),
    ]
