# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-12 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20170312_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='plan',
        ),
    ]
