# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 16:35
from __future__ import unicode_literals

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_remove_project_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model3DGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=apps.projects.models.upload_model3d_gallery_to_media)),
                ('numv', models.IntegerField()),
                ('numh', models.IntegerField()),
                ('model3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Model3D')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
