# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 04:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('demobooth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedemo',
            name='website_extra_html',
            field=tinymce.models.HTMLField(default='<iframe src="/" frameborder="0" style="position: absolute; top: 232px; left: 337px; width: 497px; height: 223px;"></iframe>', max_length=2048),
        ),
    ]
