# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stances', '0006_auto_20160612_2109'),
        ('notifications', '0003_auto_20160614_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stance',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stances.Stance'),
        ),
    ]
