# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_thread_num_posts'),
        ('notifications', '0005_remove_notification_stance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.Comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RS', 'Reply to stance comment'), ('RF', 'Reply to forum comment'), ('AG', 'Agreed with your stance'), ('LI', 'Liked your comment'), ('MT', 'Mentioned your name'), ('FM', 'Mentioned you in forums')], default='RS', max_length=2),
        ),
    ]
