# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20160721_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NQ', 'New question'), ('RS', 'Reply to stance comment'), ('RF', 'Reply to forum comment'), ('AG', 'Agreed with your stance'), ('LI', 'Liked your comment'), ('MT', 'Mentioned your name'), ('FM', 'Mentioned you in forums'), ('FW', 'Followed by other user')], default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
