# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20160518_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='author',
        ),
    ]
