# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_auto_20160629_1323'),
        ('forums', '0003_auto_20160711_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.Forum'),
        ),
    ]
