# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20160711_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='num_posts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
