# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_thread_last_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='num_posts',
            new_name='num_comments',
        ),
    ]
